"""Add cascade delete to document, query_history and collection

Revision ID: 2df55653ad28
Revises: ea8c7b511652
Create Date: 2026-06-21 01:13:56.115266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2df55653ad28'
down_revision: Union[str, Sequence[str], None] = 'ea8c7b511652'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_collection_user_id'), 'collection', ['user_id'], unique=False)
    op.drop_constraint(op.f('collection_user_id_fkey'), 'collection', type_='foreignkey')
    op.create_foreign_key(None, 'collection', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('document_collection_id_fkey'), 'document', type_='foreignkey')
    op.create_foreign_key(None, 'document', 'collection', ['collection_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('queryhistory_user_id_fkey'), 'queryhistory', type_='foreignkey')
    op.drop_constraint(op.f('queryhistory_collection_id_fkey'), 'queryhistory', type_='foreignkey')
    op.create_foreign_key(None, 'queryhistory', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'queryhistory', 'collection', ['collection_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'queryhistory', type_='foreignkey')
    op.drop_constraint(None, 'queryhistory', type_='foreignkey')
    op.create_foreign_key(op.f('queryhistory_collection_id_fkey'), 'queryhistory', 'collection', ['collection_id'], ['id'])
    op.create_foreign_key(op.f('queryhistory_user_id_fkey'), 'queryhistory', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.create_foreign_key(op.f('document_collection_id_fkey'), 'document', 'collection', ['collection_id'], ['id'])
    op.drop_constraint(None, 'collection', type_='foreignkey')
    op.create_foreign_key(op.f('collection_user_id_fkey'), 'collection', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_collection_user_id'), table_name='collection')
    # ### end Alembic commands ###
